// This file was generated by Tarmac. It is not intended for manual editing.
interface ImageSlice {
	readonly Image: string;
	readonly ImageRectOffset: Vector2;
	readonly ImageRectSize: Vector2;
}
interface Folder_TestDpi {
	L: (dpiScale: 1 | 2) => ImageSlice;
}
interface PackedSprites {
	H: ImageSlice;
	I: ImageSlice;
	J: ImageSlice;
	K: ImageSlice;
	L: ImageSlice;
	["Test Dpi"]: Folder_TestDpi;
	a: ImageSlice;
	b: ImageSlice;
	c: ImageSlice;
	d: ImageSlice;
	e: ImageSlice;
	f: ImageSlice;
	g: ImageSlice;
}
/**
 * Generated Tarmac Asset Interface
 **/
declare const PackedSprites: PackedSprites;
export = PackedSprites;
