/** This file was @generated by Tarmac. It is not intended for manual editing.  */
interface ImageSlice {
	readonly Image: string;
	readonly ImageRectOffset: Vector2;
	readonly ImageRectSize: Vector2;
}
interface Folder_TestDpi {
	L: (dpiScale: 1 | 2) => ImageSlice;
}
interface Assets {
	H: ImageSlice;
	I: ImageSlice;
	J: ImageSlice;
	K: ImageSlice;
	L: ImageSlice;
	TestDpi: Folder_TestDpi;
	a: ImageSlice;
	b: ImageSlice;
	c: ImageSlice;
	d: ImageSlice;
	e: ImageSlice;
	f: ImageSlice;
	g: ImageSlice;
}
export = Assets;
