-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	H = {
		Image = "rbxassetid://6529931885",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(512, 512),
	},
	I = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(512, 512),
	},
	J = {
		Image = "rbxassetid://6529931885",
		ImageRectOffset = Vector2.new(513, 0),
		ImageRectSize = Vector2.new(505, 505),
	},
	K = {
		Image = "rbxassetid://6529931885",
		ImageRectOffset = Vector2.new(0, 513),
		ImageRectSize = Vector2.new(505, 505),
	},
	L = {
		Image = "rbxassetid://6529931885",
		ImageRectOffset = Vector2.new(513, 506),
		ImageRectSize = Vector2.new(505, 505),
	},
	a = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(513, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
	b = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(0, 513),
		ImageRectSize = Vector2.new(128, 128),
	},
	c = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(642, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
	d = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(513, 129),
		ImageRectSize = Vector2.new(128, 128),
	},
	e = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(129, 513),
		ImageRectSize = Vector2.new(128, 128),
	},
	f = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(0, 642),
		ImageRectSize = Vector2.new(128, 128),
	},
	g = {
		Image = "rbxassetid://6529931979",
		ImageRectOffset = Vector2.new(771, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
}