-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	H = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-1.png",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(512, 512),
	},
	I = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(512, 512),
	},
	J = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-1.png",
		ImageRectOffset = Vector2.new(513, 0),
		ImageRectSize = Vector2.new(505, 505),
	},
	K = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-1.png",
		ImageRectOffset = Vector2.new(0, 513),
		ImageRectSize = Vector2.new(505, 505),
	},
	L = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-1.png",
		ImageRectOffset = Vector2.new(513, 506),
		ImageRectSize = Vector2.new(505, 505),
	},
	TestDpi = {
		L = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-3.png",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(505, 505),
				}
			else
				return {
					Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
					ImageRectOffset = Vector2.new(513, 0),
					ImageRectSize = Vector2.new(505, 505),
				}
			end
		end,
	},
	a = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(0, 513),
		ImageRectSize = Vector2.new(128, 128),
	},
	b = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(513, 506),
		ImageRectSize = Vector2.new(128, 128),
	},
	c = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(129, 513),
		ImageRectSize = Vector2.new(128, 128),
	},
	d = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(0, 642),
		ImageRectSize = Vector2.new(128, 128),
	},
	e = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(642, 506),
		ImageRectSize = Vector2.new(128, 128),
	},
	f = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(513, 635),
		ImageRectSize = Vector2.new(128, 128),
	},
	g = {
		Image = "rbxasset://.tarmac/02-spritesheets/spritesheet-2.png",
		ImageRectOffset = Vector2.new(258, 513),
		ImageRectSize = Vector2.new(128, 128),
	},
}